### ISSUE TITLE
How to change unit of temperature to celsius from fahrenheit?

### ISSUE THREAD

**Issue by Fizzify** [CleoMenezesJr/gnome-shell-extension-weather-oclock#2]
## Distro Name & Version
Pop!_OS 22.04

## GNOME Shell Version
42.5

## Other Installed Extensions
None

## Expected Behavior
The unit of the temperature displayed should be celsius.

## Current Behavior
The unit of the temperature displayed is fahrenheit.

## Detailed Description
How to change unit of temperature to celsius from fahrenheit?

**Comment by Anifyuli** [comment]
You can change Fahrenheit to Celcius from GNOME Weather

**Comment by Fizzify** [comment]
Thank you!
